name: spy-inst
channels:
  - napari/label/bundle_tools_2
  - conda-forge
dependencies:
  - boa
  - boltons
  - conda-standalone
  - constructor
  - gitpython
  - mamba
  - ruamel.yaml.jinja2
  - setuptools_scm
