name: spy-inst
channels:
  - napari/label/bundle_tools_2
  - conda-forge
dependencies:
  - boa <0.17.0  # See https://github.com/conda-forge/boa-feedstock/issues/81
  - conda-standalone
  - constructor
  - gitpython
  - mamba
  - ruamel.yaml.jinja2
  - setuptools_scm
